twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        projectname: '%projectname%'
        subtitle: 'API access to the rules of the Pathfinder RPG by Paizo.'
        paypallink: '%paypallink%'
        githublink: '%githublink%'
        changelog:
            'Oct. 3 2019':
                - '`Conditions` added'
            'Oct. 2 2019':
                - 'Druid class advancements added ğŸ»'
            'Oct. 1 2019':
                - 'Fighter class advancements added âš”ï¸'
                - '`spellsKnown` property added to character advancements'
            'Sept. 30 2019':
                - 'Changelog added ğŸ‰'
                - '`domain` and domain spells added'
                - '`description` and `role` added for classes'
                - 'added Rogue and Monk to the core classes. Somehow forgot those guys'
                - 'Bard class advancements added ğŸ¸'
